name: clean_css_transformer
author: Boris Kaul <localvoid@gmail.com>
description: Transformer that uses cleancss to minify CSS files.
homepage: https://github.com/localvoid/clean_css_transformer
version: 0.1.0
environment:
  sdk: '>=1.9.0'
dependencies:
  barback: '>=0.15.0 <0.16.0'
